FROM apache/spark:3.4.2

# Switch to root user to install dependencies and set permissions
USER root

RUN pip install --upgrade pip && \
    pip install pyspark && \
    pip install numpy && \
    pip install elasticsearch && \
    pip install requests
# Copy dataset to /tmp directory
COPY ./dataset/data.csv /tmp
#set the working directory
WORKDIR /tmp
# Switch back to the default non-root user
USER spark